# Generated by Django 5.1.2 on 2024-12-16 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbox', '0002_courseapi_promptsummary_alter_category_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseApi',
        ),
    ]
