# Generated by Django 5.1.2 on 2024-12-16 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbox', '0004_courseapi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseApi',
        ),
    ]
