# Generated by Django 5.1.2 on 2024-12-21 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbox', '0007_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='name',
            field=models.CharField(default='ASISTENTE UANDES', max_length=255),
        ),
    ]
