# Generated by Django 5.1.2 on 2024-12-30 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbox', '0008_agent_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
