# Generated by Django 5.1.2 on 2025-01-15 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbox', '0013_category_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='course_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent', to='chatbox.course'),
        ),
    ]
