# Generated by Django 5.1.2 on 2025-01-15 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbox', '0014_alter_agent_course_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='course_id',
        ),
        migrations.AddField(
            model_name='course',
            name='agent_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Courses', to='chatbox.agent'),
        ),
    ]
