# Generated by Django 5.1.2 on 2026-03-05 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbox', '0020_usercourseinteractionsummary_proxy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='prompt',
            new_name='chatbox_pro_course__c0b6ff_idx',
            old_name='chatbox_prom_course__95fd7e_idx',
        ),
        migrations.AlterField(
            model_name='agent',
            name='model',
            field=models.CharField(default='gpt-5-mini', max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
