# Generated by Django 5.1.2 on 2026-04-07 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbox', '0024_course_current_agent_prompt_agent_usercourse_agent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='prompt',
            new_name='chatbox_pro_course__079041_idx',
            old_name='chatbox_pro_course__41f5c3_idx',
        ),
        migrations.RenameIndex(
            model_name='prompt',
            new_name='chatbox_pro_interac_e1d52e_idx',
            old_name='chatbox_prom_interac_8d95f8_idx',
        ),
        migrations.AlterField(
            model_name='agent',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompts', to='chatbox.category'),
        ),
    ]
