# Generated by Django 5.1.2 on 2026-07-21 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbox', '0025_rename_chatbox_pro_course__41f5c3_idx_chatbox_pro_course__079041_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('active_from', models.DateField(blank=True, null=True)),
                ('active_until', models.DateField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_schedules', to='chatbox.course')),
            ],
            options={
                'ordering': ('course__title', 'weekday', 'start_time'),
                'indexes': [models.Index(fields=['course', 'weekday', 'start_time', 'end_time'], name='chatbox_cou_course__20d2a5_idx')],
            },
        ),
    ]
